const data=[
        "The Shawshank Redemption",
        "The Godfather",
        "The Dark Knight",
        "12 Angry Men",
        "Schindler's List",
        "Pulp Fiction",
        "The Lord of the Rings",
        "The Good, the Bad and the Ugly",
        "Fight Club",
        "Forrest Gump",
        "Inception",
        "Star Wars",
        "The Lord of the Rings",
        "One Flew Over the Cuckoo's Nest",
        "Goodfellas",
        "The Matrix",
        "Seven Samurai",
        "Star Wars: Episode IV",
        "City of God",
        "Se7en",
        "The Silence of the Lambs",
        "It's a Wonderful Life",
        "Life Is Beautiful",
        "The Usual Suspects",
        "Léon: The Professional",
        "Spirited Away",
        "Saving Private Ryan",
        "The Green Mile",
        "Interstellar",
        "Parasite"
]

export default data